package codex

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

type MockRunner struct {
	Delay time.Duration
}

func NewMockRunnerFromEnv() MockRunner {
	ms, _ := strconv.Atoi(strings.TrimSpace(os.Getenv("AUTO_GARDENER_MOCK_DELAY_MS")))
	return MockRunner{Delay: time.Duration(ms) * time.Millisecond}
}

func (r MockRunner) Run(ctx context.Context, req RunRequest) RunResult {
	prompt := req.Prompt
	emit := func(line string) {
		if req.OnLine != nil {
			req.OnLine(line)
		}
	}
	if r.Delay > 0 {
		select {
		case <-time.After(r.Delay):
		case <-ctx.Done():
			return RunResult{Err: ctx.Err()}
		}
	}
	emit("mock: started " + strings.TrimSpace(req.Role))
	var output string
	switch {
	case strings.Contains(prompt, "Git 统一初始化"):
		output = "Mock git initialization complete."
	case req.Role == "gardener" && (strings.Contains(prompt, "已经结束") || strings.Contains(prompt, "决策") || strings.Contains(prompt, "判断")):
		output = `{"message_to_user":"Mock run finished successfully.","forest_finished":true,"trees":[]}`
	case req.Role == "gardener":
		output = `{"message_to_user":"Mock planner created one implementation task.","forest_finished":false,"trees":[{"name":"Mock implementation","objective":"Create a mock deliverable","prompt":"Create a small mock deliverable and report completion.","scope":["mock-output"]}]}`
	case strings.Contains(prompt, "验证子任务"):
		output = "# Mock validation report\n\nGoal status: complete\n\nValidation passed."
	default:
		output = "# Mock task report\n\nGoal status: complete\n\nCreated mock deliverable.\n"
		if req.WorkDir != "" {
			_ = os.MkdirAll(req.WorkDir, 0755)
			_ = writeMockDeliverable(filepath.Join(req.WorkDir, "mock-deliverable.md"))
		}
	}
	emit("mock: completed " + strings.TrimSpace(req.Role))
	if req.OutputFile != "" {
		if err := os.MkdirAll(filepath.Dir(req.OutputFile), 0755); err != nil {
			return RunResult{Output: output, Err: err}
		}
		if err := os.WriteFile(req.OutputFile, []byte(output), 0644); err != nil {
			return RunResult{Output: output, Err: err}
		}
	}
	if strings.Contains(prompt, "MOCK_FAIL") {
		return RunResult{Output: output, Err: fmt.Errorf("mock failure requested")}
	}
	return RunResult{Output: output}
}

func writeMockDeliverable(path string) error {
	if info, err := os.Lstat(path); err == nil && info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing to write mock deliverable symlink")
	}
	return os.WriteFile(path, []byte("# Mock deliverable\n\nGenerated by Gardener mock runner.\n"), 0644)
}
